[browser]
gatherUsageStats = false
favicon = "/favicon.png"

[client]
showErrorDetails = true

[logger]
level = "debug"

[server]
headless = true
enableXsrfProtection = true
maxUploadSize = 10
port = 8080
runOnSave = false